### PR TITLE
89: harmonized groupId and artifactId

### PR DESCRIPTION
**Pull request by thodorisbais**
Signed-off-by: Thodoris Bais <thodoris.bais@gmail.com>

### CODE REVIEW

**Comment by ggam** [comment]
What was the final outcome of this discussion?

**Comment by arjantijms** [comment]
> What was the final outcome of this discussion?

This PR can me merged as soon as the PMC approves our request, and when the subsequent permissions have been given to deploy to the new group id.

**Comment by thodorisbais** [comment]
@arjantijms is there something we could do in order to give that an extra boost? It looks like we've already been idle for a while :-) Or am I just missing some process-related background here?

**Comment by arjantijms** [comment]
@thodorisbais The process has been initiated here: https://eclipse.org/lists/ee4j-pmc/msg02587.html

Ivar already +1'ed

**Comment by thodorisbais** [comment]
@arjantijms good one, I wasn't following that mailing list, thanks a lot!

**Comment by arjantijms** [comment]
Okay then, here we go :)

**Pull request merged**
